#!/usr/bin/env bash
#
# [wp] - simple X wallpaper setter with optional
# interactive mode and save/restore functionality.
#
# Copyright 2016 Armin Jenewein (@netzverweigerer on GitHub)
#
# wp is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# wp is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with wp. If not, see <http://www.gnu.org/licenses/>.
#

# path to wallpaper directory (this is likely the only
# thing you need to change...)
dir="$HOME/Pictures"

banner () {
  tput setaf 12
  echo -n "["
  tput setaf 7
  echo -n "wp"
  tput setaf 12
  echo -n "]"
  tput sgr0
  echo -n " "
}

banner

usage () {
  echo -n "USAGE: "
  echo "wp [OPTIONS]"
  echo ""
  echo "OPTIONS: "
  echo "--set|-s <file>             Sets <file> as wallpaper image"
  echo "--get|-g                    Gets the currently saved wallpaper file"
  echo "--random|-r                 Sets a random wallpaper"
  echo "--restore                   Restores (sets) saved wallpaper"
  echo "--interactive|-i            Start interactive mode"
  echo "--help|-h                   This help information"
  echo
}

shopt -s globstar
array=($dir/**)
totalcount="${#array[@]}"

set () {
  file="$1"
  f="$(readlink -f $file)"
  mkdir -p $HOME/.wp
  echo "Setting wallpaper: ${f##*/}"
  feh --bg-fill "$file" && \
  if [[ ! -h "$file" ]]; then
    banner
    echo "Updating symlink: $HOME/.wp/current"
    # echo "$file" > $HOME/.wp/current
    unlink $HOME/.wp/current
    # echo "DEBUG: file: $file (readlink: $(readlink -f $file)"
    ln -s $file $HOME/.wp/current
  fi
}

restore () {
  banner
  set $HOME/.wp/current
}

get () {
  readlink -f $HOME/.wp/current
}

random () {
echo "Using wallpaper directory: $dir"
banner
echo "Total number of wallpapers found: $totalcount"

 if [[ "$(uname)" == FreeBSD ]]; then
    randomindex="$(shuffle -p 1 $(seq 1 ${totalcount}))"
	  randomindex=$((randomindex-1))
   banner
   echo "Using random index: $randomindex"
  else
    randomindex="$(shuf -i 1-${totalcount} -n 1)"
	  randomindex=$((randomindex-1))
    banner
   echo "Using random index: $randomindex"
  fi
  banner
	file=${array[$randomindex]}
  set "$file"
}

handler () {
  read -s -n 1 reply
  case "$reply" in
    n)
      random
    ;;
    q)
      echo "Bye..."
      exit 0
    ;;
  esac
}

interactive () {
  echo "Interactive Mode. Keys: [n]ext [q]uit"
  while true; do
    banner
    handler
  done
}

case "$1" in
  --set|-s)
    shift
    set "$1"
  ;;
  --get|-g)
    get
  ;;
  --random|-z)
    random
  ;;
  --restore|-r)
    restore 
  ;;
  --interactive|-i)
    interactive
  ;;
  --help|--usage|-h|--)
    usage
  ;;
  '')
    echo "No option specified. Setting a random wallpaper."
    banner
    echo "Use --help for usage help."
    banner
    random
  ;;
  *)
    usage
  ;;
esac



